<?php
/**
 * CodeTable
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SKY\NXT\DataIntegration
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NXT Data Integration
 *
 * This API supports an expanded set of endpoints optimized for data integration scenarios.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SKY\NXT\DataIntegration\Model;

use ArrayAccess;
use SKY\NXT\DataIntegration\ObjectSerializer;

/**
 * CodeTable Class Doc Comment
 *
 * @category Class
 * @description A Code Table record from the dbo.CodeTables table in Raiser&#39;s Edge.
 * @package  SKY\NXT\DataIntegration
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CodeTable implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CodeTable';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'codeTablesId' => 'int',
        'name' => 'string',
        'userDefined' => 'bool',
        'hasShortDescription' => 'bool',
        'shortDescriptionLength' => 'int',
        'hiddenSystemTable' => 'bool',
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'codeTablesId' => 'int32',
        'name' => null,
        'userDefined' => null,
        'hasShortDescription' => null,
        'shortDescriptionLength' => 'int32',
        'hiddenSystemTable' => null,
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'codeTablesId' => false,
        'name' => true,
        'userDefined' => false,
        'hasShortDescription' => false,
        'shortDescriptionLength' => false,
        'hiddenSystemTable' => false,
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'codeTablesId' => 'code_tables_id',
        'name' => 'name',
        'userDefined' => 'user_defined',
        'hasShortDescription' => 'has_short_description',
        'shortDescriptionLength' => 'short_description_length',
        'hiddenSystemTable' => 'hidden_system_table',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'codeTablesId' => 'setCodeTablesId',
        'name' => 'setName',
        'userDefined' => 'setUserDefined',
        'hasShortDescription' => 'setHasShortDescription',
        'shortDescriptionLength' => 'setShortDescriptionLength',
        'hiddenSystemTable' => 'setHiddenSystemTable',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'codeTablesId' => 'getCodeTablesId',
        'name' => 'getName',
        'userDefined' => 'getUserDefined',
        'hasShortDescription' => 'getHasShortDescription',
        'shortDescriptionLength' => 'getShortDescriptionLength',
        'hiddenSystemTable' => 'getHiddenSystemTable',
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('codeTablesId', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('userDefined', $data ?? [], null);
        $this->setIfExists('hasShortDescription', $data ?? [], null);
        $this->setIfExists('shortDescriptionLength', $data ?? [], null);
        $this->setIfExists('hiddenSystemTable', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets codeTablesId
     *
     * @return int|null
     */
    public function getCodeTablesId()
    {
        return $this->container['codeTablesId'];
    }

    /**
     * Sets codeTablesId
     *
     * @param int|null $codeTablesId The unique identifier for the code table.
     *
     * @return self
     */
    public function setCodeTablesId($codeTablesId)
    {
        if (is_null($codeTablesId)) {
            throw new \InvalidArgumentException('non-nullable codeTablesId cannot be null');
        }
        $this->container['codeTablesId'] = $codeTablesId;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name The name of the code table.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            array_push($this->openAPINullablesSetToNull, 'name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('name', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets userDefined
     *
     * @return bool|null
     */
    public function getUserDefined()
    {
        return $this->container['userDefined'];
    }

    /**
     * Sets userDefined
     *
     * @param bool|null $userDefined Indicates whether the code table is user defined.
     *
     * @return self
     */
    public function setUserDefined($userDefined)
    {
        if (is_null($userDefined)) {
            throw new \InvalidArgumentException('non-nullable userDefined cannot be null');
        }
        $this->container['userDefined'] = $userDefined;

        return $this;
    }

    /**
     * Gets hasShortDescription
     *
     * @return bool|null
     */
    public function getHasShortDescription()
    {
        return $this->container['hasShortDescription'];
    }

    /**
     * Sets hasShortDescription
     *
     * @param bool|null $hasShortDescription The value indicating whether the code table has a short description.
     *
     * @return self
     */
    public function setHasShortDescription($hasShortDescription)
    {
        if (is_null($hasShortDescription)) {
            throw new \InvalidArgumentException('non-nullable hasShortDescription cannot be null');
        }
        $this->container['hasShortDescription'] = $hasShortDescription;

        return $this;
    }

    /**
     * Gets shortDescriptionLength
     *
     * @return int|null
     */
    public function getShortDescriptionLength()
    {
        return $this->container['shortDescriptionLength'];
    }

    /**
     * Sets shortDescriptionLength
     *
     * @param int|null $shortDescriptionLength The length of the short description.
     *
     * @return self
     */
    public function setShortDescriptionLength($shortDescriptionLength)
    {
        if (is_null($shortDescriptionLength)) {
            throw new \InvalidArgumentException('non-nullable shortDescriptionLength cannot be null');
        }
        $this->container['shortDescriptionLength'] = $shortDescriptionLength;

        return $this;
    }

    /**
     * Gets hiddenSystemTable
     *
     * @return bool|null
     */
    public function getHiddenSystemTable()
    {
        return $this->container['hiddenSystemTable'];
    }

    /**
     * Sets hiddenSystemTable
     *
     * @param bool|null $hiddenSystemTable The value indicating whether the code table is a hidden system table.
     *
     * @return self
     */
    public function setHiddenSystemTable($hiddenSystemTable)
    {
        if (is_null($hiddenSystemTable)) {
            throw new \InvalidArgumentException('non-nullable hiddenSystemTable cannot be null');
        }
        $this->container['hiddenSystemTable'] = $hiddenSystemTable;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
