#!/usr/bin/env php
<?php

use Battis\DataUtilities\Path;
use Battis\OpenAPI\CLI\Map;
use cebe\openapi\spec\OpenApi;

require __DIR__ . "/../vendor/autoload.php";

class BlackbaudMap extends Map {
  protected function getNamespaceFromSpec(string $specPath, OpenApi $spec, string $baseNamespace): string
  {
    return Path::join("\\",array_merge([$baseNamespace], explode(" ", $spec->info->title)));
  }
  
  protected function getBasePathFromSpec(string $specPath, OpenApi $spec, string $basePath): string
  {
    return Path::join(array_merge([$basePath], explode(" ", $spec->info->title)));  
  }
}

$map = new BlackbaudMap();
$map->run();